train_set: ./data/data_v2/anns/refcoco/train.json
evaluate_set: ./data/data_v2/anns/refcoco/val.json
seg_gt_path: ./data/data_v2/masks/refcoco
log_path: ./log/refcoco
evaluate_model: ./log/refcoco_example/models/best_map.h5

transformer_encoder_num: 2
transformer_decoder_num: 2

batch_size: 128
workers: 32

num_query: 16
query_balance: True